### ISSUE TITLE
Taskbar on Win11

### ISSUE THREAD

**Issue by wowmjau** [JairusSW/Chess.com#5]
right clicking on taskbar icon on win11 does not pull up settings

also is there anyway to put it in fullscreen

**Comment by wowmjau** [comment]
taskbar issue solved need help with fullscreen still

**Comment by JairusSW** [comment]
Did you figure this out?

**Comment by wowmjau** [comment]
Yes, thank you

**Comment by nullablepointer** [comment]
> Yes, thank you

how did you fix this?

**Comment by nullablepointer** [comment]
nvm was too dumb to realize it was the tray, not the taskbar
